name: Create and publish a Docker image

on:
  push:
    tags:
        - '[0-9]+.[0-9]+.[0-9]+'

env:
  REGISTRY: ghcr.io

permissions:
    contents: read
    packages: write  

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set env
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

            - name: Log in to the Container registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  file: app/Dockerfile
                  context: app
                  push: true
                  tags: ${{ env.REGISTRY }}/vanny96/hello-world:${{env.RELEASE_VERSION}} , ${{ env.REGISTRY }}/vanny96/hello-world:latest

    update-manifest:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set env
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

            - name: Test creating and pushing file
              run: |
                echo "Test file" > manifest/testfile.context
                git remote set-url origin ${{ secrets.ssh }}
                git add .
                git commit -m "Creates file"
                git push origin master