name: Create and publish a Docker image

on:
  push:
    branches:
        - 'master'

env:
  REGISTRY: ghcr.io

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Log in to the Container registry
          uses: docker/login-action@v2
          with:
              registry: ${{ env.REGISTRY }}
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v4
          with:
              context: ./app
              push: true
              tags: ${{ env.REGISTRY }}/vanny96/hello-world:1.0